const IDENTITY_TYPES = [
  { identityTypeId: 1, description: "Jan Aadhaar Id" },
  { identityTypeId: 2, description: "Jan Aadhaar Ack Id" },
  { identityTypeId: 3, description: "Mobile Number" },
  { identityTypeId: 4, description: "Aadhaar Id" },
  { identityTypeId: 5, description: "House Hold Id" },
  { identityTypeId: 6, description: "Abha Address" },
  { identityTypeId: 7, description: "Abha Number" },
  { identityTypeId: 8, description: "Ration Card" },
];

const initialFormData = {
  rtaCase: "no",
  admissionType: "normal",
  hasJanAadhaar: true,
  patientName: "",
  patientAge: "",
  gender: "",
  isMlcCase: false,
  assaultType: "",
  isPatientIdentified: false,
  identifierName: "",
  identifierRelation: "",
  identifierContact: "",
  identityType: "",
  identityNumber: "",
  entitlementType: "",
  rationCard: "",
  mobileNo: "",
  houseNumber: "",
  street: "",
  block: "",
  gramPanchayat: "",
  village: "",
  tehsil: "",
  district: "",
  stateName: "",
  pinCode: "",
  bhamashaId: "",
  janAadhaarId: "",
  memberName: "",
  memberAge: "",
  memberGender: "",
  memberRelation: "",
  memberId: "",
  photo: null,
  verifyMethod: "aadhaar",
};

export { IDENTITY_TYPES, initialFormData };
